spring.application.name=shoe-fast-be
server.port=8086
spring.datasource.username=postgres
server.tomcat.accesslog.enabled=true
spring.datasource.password=azEryMn01EPBxHczti6gEnIB3cSCIZ2024
#for local
spring.datasource.url=jdbc:postgresql://37.27.49.227/shoe?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&reWriteBatchedInserts=true

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

